package com.bolingx.ai.util;

public interface Constant {

    String MESSAGE_CODE_USER_OR_PASSWD_ERROR = "40100";

    String MESSAGE_CODE_USER_NOT_EXIST= "40101";

    String MESSAGE_CODE_USERNAME_EXIST = "40150";

    String MESSAGE_CODE_EMAIL_EXIST = "40151";

    String MESSAGE_CODE_NOT_BINDING_EMAIL = "40152";

    String MESSAGE_CODE_CAPTCHA_EXPIRED = "40200";

    String MESSAGE_CODE_CAPTCHA_ERROR = "40201";
}
